#!/usr/bin/env bash
set -euo pipefail

GAME_DIR_DEFAULT="$HOME/Library/Application Support/Steam/steamapps/common/Cyberpunk 2077"
GAME_DIR="${1:-$GAME_DIR_DEFAULT}"

INPUT_USER="$GAME_DIR/r6/config/inputUserMappings.xml"
INPUT_CTX="$GAME_DIR/r6/config/inputContexts.xml"
INPUT_CTX_MAC="$GAME_DIR/r6/config/inputContexts_mac.xml"
CACHE_USER="$GAME_DIR/r6/cache/inputUserMappings.xml"
CACHE_CTX="$GAME_DIR/r6/cache/inputContexts.xml"
R6_INPUT_DIR="$GAME_DIR/r6/input"
OVERLAY_XML="$R6_INPUT_DIR/mods.xml"
SCRIPTS_DIR="$GAME_DIR/r6/scripts"

if [[ ! -f "$INPUT_USER" ]]; then
  echo "Missing: $INPUT_USER" >&2
  exit 1
fi
if [[ ! -f "$INPUT_CTX" ]]; then
  echo "Missing: $INPUT_CTX" >&2
  exit 1
fi

python3 - "$INPUT_USER" "$INPUT_CTX" "$INPUT_CTX_MAC" <<'PY'
import sys
from pathlib import Path
import re

input_user = Path(sys.argv[1])
input_ctx = Path(sys.argv[2])
input_ctx_mac = Path(sys.argv[3])

game_dir = input_user.parents[2]  # <game>/r6/config/inputUserMappings.xml -> <game>
r6_input_dir = game_dir / "r6" / "input"
overlay_xml = r6_input_dir / "mods.xml"
r6_scripts_dir = game_dir / "r6" / "scripts"

def backup(p: Path) -> None:
    b = p.with_suffix(p.suffix + ".bak")
    if not b.exists():
        b.write_bytes(p.read_bytes())

def patch_input_user(p: Path) -> bool:
    s = p.read_text(encoding="utf-8", errors="replace")
    changed = False
    idx = s.rfind("</bindings>")
    if idx == -1:
        raise RuntimeError("Couldn't find </bindings> in inputUserMappings.xml")

    inserts = []
    if 'mapping name="modmenu_toggle"' not in s:
        inserts.append(
            "\n\t<!-- ModMenu v0.1 -->\n"
            '\t<mapping name="modmenu_toggle" type="Button" >\n'
            '\t\t<button id="IK_F10" />\n'
            "\t</mapping>\n"
        )
        changed = True

    # ImmersiveTimeskip hotkey (default O). The script listens for action "immersive_time_skip".
    if 'mapping name="immersive_time_skip"' not in s:
        inserts.append(
            "\n\t<!-- ImmersiveTimeskip -->\n"
            '\t<mapping name="immersive_time_skip" type="Button" >\n'
            '\t\t<button id="IK_O" />\n'
            "\t</mapping>\n"
        )
        changed = True

    if not inserts:
        return False

    insert = "".join(inserts)
    s2 = s[:idx] + insert + s[idx:]
    p.write_text(s2, encoding="utf-8")
    return changed

def patch_input_contexts(p: Path) -> bool:
    s = p.read_text(encoding="utf-8", errors="replace")
    changed = False
    start = s.find('<context name="Exploration"')
    if start == -1:
        raise RuntimeError('Couldn\'t find <context name="Exploration"> in inputContexts.xml')
    end = s.find("</context>", start)
    if end == -1:
        raise RuntimeError("Couldn't find closing </context> for Exploration in inputContexts.xml")

    inserts = []
    if 'action name="modmenu_toggle"' not in s:
        inserts.append('\n\t\t<!-- ModMenu v0.1 -->\n\t\t<action name="modmenu_toggle"\t\t\tmap="modmenu_toggle" />\n')
        changed = True
    if 'action name="immersive_time_skip"' not in s:
        inserts.append(
            '\n\t\t<!-- ImmersiveTimeskip -->\n\t\t<action name="immersive_time_skip"\t\t\tmap="immersive_time_skip" />\n'
        )
        changed = True

    if not inserts:
        return False

    insert = "".join(inserts)
    s2 = s[:end] + insert + s[end:]
    p.write_text(s2, encoding="utf-8")
    return changed

backup(input_user)
backup(input_ctx)
if input_ctx_mac.exists():
    backup(input_ctx_mac)

changed_user = patch_input_user(input_user)
changed_ctx = patch_input_contexts(input_ctx)
changed_ctx_mac = patch_input_contexts(input_ctx_mac) if input_ctx_mac.exists() else False

print(f"patched_inputUserMappings={changed_user}")
print(f"patched_inputContexts={changed_ctx}")
print(f"patched_inputContexts_mac={changed_ctx_mac}")

# Also emit an overlay for Input Loader / re-merge workflows.
# This helps when caches are rebuilt without our base-file edits being present (or if the user restores backups).
r6_input_dir.mkdir(parents=True, exist_ok=True)
overlay_xml.write_text(
    """<?xml version="1.0" encoding="utf-8"?>
<bindings>
  <!-- Generated by cp2077-modmenu/tools/patch_input.sh -->

  <!-- inputUserMappings.xml nodes -->
  <mapping name="modmenu_toggle" type="Button" append="true">
    <button id="IK_F10" />
  </mapping>
  <mapping name="immersive_time_skip" type="Button" append="true">
    <button id="IK_O" />
  </mapping>

  <!-- inputContexts.xml nodes -->
  <context name="Exploration" append="true">
    <action name="modmenu_toggle" map="modmenu_toggle" />
    <action name="immersive_time_skip" map="immersive_time_skip" />
  </context>
</bindings>
""",
    encoding="utf-8",
)
print(f"wrote_overlay={overlay_xml}")

# Scanner: look for script hotkey actions and report missing config entries.
def scan_script_actions(root: Path) -> set[str]:
    if not root.exists():
        return set()
    actions: set[str] = set()
    # ListenerAction.IsAction(action, n"...")
    pat_listener = re.compile(r"\bListenerAction\.IsAction\s*\(\s*[^,\n]+,\s*n\"([^\"]+)\"")
    for reds in root.rglob("*.reds"):
        try:
            text = reds.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        actions.update(pat_listener.findall(text))
    return actions

def file_contains(p: Path, needle: str) -> bool:
    try:
        return needle in p.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False

script_actions = scan_script_actions(r6_scripts_dir)
if script_actions:
    missing_actions: list[str] = []
    missing_mappings: list[str] = []
    for a in sorted(script_actions):
        # Treat action name and mapping name as identical (common mod pattern).
        if not file_contains(input_ctx, f'action name="{a}"'):
            missing_actions.append(a)
        if input_ctx_mac.exists() and not file_contains(input_ctx_mac, f'action name="{a}"'):
            missing_actions.append(f"{a} (mac)")
        if not file_contains(input_user, f'mapping name="{a}"'):
            missing_mappings.append(a)
    if missing_actions or missing_mappings:
        print("scan_result=missing")
        if missing_actions:
            print("missing_actions=" + ",".join(missing_actions))
        if missing_mappings:
            print("missing_mappings=" + ",".join(missing_mappings))
    else:
        print("scan_result=ok")
else:
    print("scan_result=skipped (no r6/scripts/*.reds found)")
PY

echo "Done."
echo "Recommended: delete cached input files so the game rebuilds them:"
echo "  rm -f \"$CACHE_USER\" \"$CACHE_CTX\""
echo "Overlay written to:"
echo "  \"$OVERLAY_XML\""

